name: Publish to Hex.pm

on:
  release:
    types: [released]

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish to Hex.pm
    runs-on: ubuntu-latest
    env:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
    steps:
      - uses: actions/checkout@v6

      - name: Set up Elixir
        id: setup-beam
        uses: erlef/setup-beam@v1
        with:
          version-file: '.tool-versions'
          version-type: 'strict'

      - name: Restore dependencies cache
        uses: actions/cache@v5
        with:
          path: deps
          key: ${{ runner.os }}-publish-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-publish-mix-${{ steps.setup-beam.outputs.otp-version }}-${{ steps.setup-beam.outputs.elixir-version }}-

      - name: Install dependencies
        run: mix deps.get

      - name: Publish to Hex.pm
        run: mix hex.publish --yes
